description: Math expression processor language for solve congruence equations
footer-links:
  github: agustin-del-pino

exclude:
  - LICENSE
  - README.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true